version: '3.9'
services:
  db:
    image: postgres:14-alpine
    container_name: dtrivia_db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - dtrivia_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${DATABASE_NAME}", "-U", "${DATABASE_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dtrivia_db:
